# Generated by Django 4.2.7 on 2023-11-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
