# Generated by Django 4.2.7 on 2023-11-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_file_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='files',
        ),
        migrations.AddField(
            model_name='submission',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.file'),
        ),
    ]
