# Generated by Django 4.2.7 on 2023-11-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_submission_files_submission_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='remarks',
            field=models.CharField(default='', max_length=255),
        ),
    ]
