# Generated by Django 4.2.7 on 2023-11-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_pysicalsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PysicalSubmission',
        ),
    ]
