# Generated by Django 4.2.7 on 2023-11-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_pysicalsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
