# Generated by Django 4.2.7 on 2023-11-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_submission_status_alter_bills_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='remarks',
        ),
        migrations.AddField(
            model_name='bills',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='bills',
            name='remarks',
            field=models.CharField(default='', max_length=255),
        ),
    ]
