# Generated by Django 4.2.7 on 2023-11-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_bills_status_bills_remarkadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
