# Generated by Django 4.2.7 on 2023-11-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_submission_text_submission_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='remarks',
        ),
    ]
