# Generated by Django 4.2.7 on 2023-11-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_bills_remarkadmin_remove_bills_remarkmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.SlugField(default='P'),
        ),
    ]
