# Generated by Django 4.2.7 on 2023-11-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
        migrations.AddField(
            model_name='submission',
            name='howmuch',
            field=models.IntegerField(null=True),
        ),
    ]
