# Generated by Django 4.2.7 on 2023-11-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_submission_status_submission_howmuch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='howmuch',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
