# Generated by Django 4.2.7 on 2023-11-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_submission_howmuch_submission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='status',
        ),
    ]
