# Generated by Django 4.2.7 on 2023-12-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_submission_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='remarks',
            new_name='remarks_admin',
        ),
        migrations.AddField(
            model_name='bills',
            name='remarks_member',
            field=models.CharField(default='', max_length=255),
        ),
    ]
