# Generated by Django 4.2.7 on 2023-12-01 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0026_rename_remarks_bills_remarks_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='')),
                ('assigned', models.DateField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.room')),
                ('selected_admins', models.ManyToManyField(related_name='selected_contributions_admin', to='base.admin')),
                ('selected_members', models.ManyToManyField(related_name='selected_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Group Contributions',
            },
        ),
    ]
