# Generated by Django 4.2.7 on 2023-12-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_events'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table=None,
        ),
    ]
