# Generated by Django 4.2.7 on 2023-12-02 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_events_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='room',
        ),
    ]
