# Generated by Django 4.2.7 on 2023-12-02 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_events_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='room',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.room'),
        ),
    ]
