# Generated by Django 4.2.7 on 2023-12-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_profile_admin_profile_member_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile',
        ),
        migrations.AddField(
            model_name='admin',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profileimg',
            field=models.ImageField(default='blank-profile.jpg', upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
