# Generated by Django 4.2.7 on 2023-12-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_announcement_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
