# Generated by Django 4.2.7 on 2023-12-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_announcement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='remarks_member',
        ),
    ]
