# Generated by Django 4.2.7 on 2023-12-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_remove_bills_remarks_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='remarks_member',
            field=models.CharField(default='', max_length=255),
        ),
    ]
