# Generated by Django 4.2.7 on 2023-12-11 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_submission_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='is_paid',
        ),
    ]
