# Generated by Django 4.2.7 on 2023-12-11 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_bills_remarks_admin_alter_bills_remarks_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='remarks_admin',
        ),
    ]
