# Generated by Django 4.2.8 on 2023-12-12 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0050_remove_bills_remarks_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='remarks_member',
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bills')),
            ],
        ),
    ]
