# Generated by Django 5.0 on 2023-12-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_remove_bills_remarks_member_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
